services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=meddi
      - PGDATA=/var/lib/pg_data
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    env_file: '.env'
    ports:
      - '3000:3000'
    depends_on:
      - postgres